# Generated by Django 5.0 on 2024-01-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='company',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
    ]
